name: 'Delombok'
description: 'Delombok the given directory'
inputs:
  directory:
    description: 'Path to the workspace directory'
    required: false
    default: ${{ github.workspace }}
  sourcePath:
    description: 'Path relative to workspace directory where source files are'
    required: false
    default: src

runs:
  using: "composite"
  steps:
    - run: |
        echo "Action path: ${{ github.action_path }}"
        echo "Input directory: ${{ inputs.directory }}"
        echo "Start delomboking..."
        ${{ github.action_path }}/delombok.sh "${{ inputs.directory }}" "${{ inputs.sourcePath }}"
      shell: bash
