name: 'Delombok'
description: 'Delombok the given directory'
inputs:
  directory:
    description: 'Path to the directory to delombok (the project workspace)'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - run: |
        echo "Action path: ${{ github.action_path }}"
        echo "Input directory: ${{ inputs.directory }}"
        echo "Start delomboking..."
        ${{ github.action_path }}/delombok.sh "${{ inputs.directory }}"
      shell: bash
