name: 'Delombok'
description: 'Delombok the given directory'
inputs:
  directory:
    description: 'Path to the workspace directory'
    required: false
    default: ${{ github.workspace }}
  sourcePath:
    description: 'Path relative to workspace directory where source files are'
    required: false
    default: src
  printDelombokSource:
    description: 'Whether to print the delomboked source files (true|false)'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - run: |
        echo "Action path: ${{ github.action_path }}"
        echo "Inputs:"
        echo "  directory: ${{ inputs.directory }}"
        echo "  sourcePath: ${{ inputs.sourcePath }}"
        echo "  printDelombokSource: ${{ inputs.printDelombokSource }}"
        echo "Start delomboking..."
        ${{ github.action_path }}/delombok.sh "${{ inputs.directory }}" "${{ inputs.sourcePath }}" "${{ inputs.printDelombokSource }}"
      shell: bash
